// This file is generated by `npm run generate:indices`.
// Do not edit it manually.


import locations__alma from "./locations/alma";
import locations__amanda from "./locations/amanda";
import locations__ankersaal from "./locations/ankersaal";
import locations__arkade from "./locations/arkade";
import locations__babylonHelsinki from "./locations/babylon-helsinki";
import locations__columbiaroad from "./locations/columbiaroad";
import locations__dipoli from "./locations/dipoli";
import locations__elisaAppelsiini from "./locations/elisa-appelsiini";
import locations__futurice from "./locations/futurice";
import locations__gofore from "./locations/gofore";
import locations__hbc from "./locations/hbc";
import locations__internet from "./locations/internet";
import locations__loihdefactor from "./locations/loihdefactor";
import locations__nitor from "./locations/nitor";
import locations__paasitorni from "./locations/paasitorni";
import locations__poliisienkesakoti from "./locations/poliisienkesakoti";
import locations__porssitalo from "./locations/porssitalo";
import locations__rantasauna from "./locations/rantasauna";
import locations__rooftopmiami from "./locations/rooftopmiami";
import locations__saeWien from "./locations/sae-wien";
import locations__tiivistamo from "./locations/tiivistamo";
import locations__tuas from "./locations/tuas";
import locations__upcloud from "./locations/upcloud";
import locations__valkoinenSali from "./locations/valkoinen-sali";
import locations__wuWien from "./locations/wu-wien";
import locations__yle from "./locations/yle";

export const locations = {
  alma: locations__alma,
  amanda: locations__amanda,
  ankersaal: locations__ankersaal,
  arkade: locations__arkade,
  babylonHelsinki: locations__babylonHelsinki,
  columbiaroad: locations__columbiaroad,
  dipoli: locations__dipoli,
  elisaAppelsiini: locations__elisaAppelsiini,
  futurice: locations__futurice,
  gofore: locations__gofore,
  hbc: locations__hbc,
  internet: locations__internet,
  loihdefactor: locations__loihdefactor,
  nitor: locations__nitor,
  paasitorni: locations__paasitorni,
  poliisienkesakoti: locations__poliisienkesakoti,
  porssitalo: locations__porssitalo,
  rantasauna: locations__rantasauna,
  rooftopmiami: locations__rooftopmiami,
  saeWien: locations__saeWien,
  tiivistamo: locations__tiivistamo,
  tuas: locations__tuas,
  upcloud: locations__upcloud,
  valkoinenSali: locations__valkoinenSali,
  wuWien: locations__wuWien,
  yle: locations__yle,
} as const;

export const alma = locations.alma;
export const amanda = locations.amanda;
export const ankersaal = locations.ankersaal;
export const arkade = locations.arkade;
export const babylonHelsinki = locations.babylonHelsinki;
export const columbiaroad = locations.columbiaroad;
export const dipoli = locations.dipoli;
export const elisaAppelsiini = locations.elisaAppelsiini;
export const futurice = locations.futurice;
export const gofore = locations.gofore;
export const hbc = locations.hbc;
export const internet = locations.internet;
export const loihdefactor = locations.loihdefactor;
export const nitor = locations.nitor;
export const paasitorni = locations.paasitorni;
export const poliisienkesakoti = locations.poliisienkesakoti;
export const porssitalo = locations.porssitalo;
export const rantasauna = locations.rantasauna;
export const rooftopmiami = locations.rooftopmiami;
export const saeWien = locations.saeWien;
export const tiivistamo = locations.tiivistamo;
export const tuas = locations.tuas;
export const upcloud = locations.upcloud;
export const valkoinenSali = locations.valkoinenSali;
export const wuWien = locations.wuWien;
export const yle = locations.yle;

import people__aapeli from "./people/aapeli";
import people__aarniKoskela from "./people/aarni-koskela";
import people__adamMiskiewicz from "./people/adam-miskiewicz";
import people__aleksandra from "./people/aleksandra";
import people__aleksiPousar from "./people/aleksi-pousar";
import people__alexBooker from "./people/alex-booker";
import people__anastasiia from "./people/anastasiia";
import people__andreas from "./people/andreas";
import people__andrei from "./people/andrei";
import people__andrewRhyne from "./people/andrew-rhyne";
import people__andreyG from "./people/andrey-g";
import people__andreyOkonetchnikov from "./people/andrey-okonetchnikov";
import people__annaDoubkova from "./people/anna-doubkova";
import people__ante from "./people/ante";
import people__artemSapegin from "./people/artem-sapegin";
import people__artemZakharchenko from "./people/artem-zakharchenko";
import people__aurora from "./people/aurora";
import people__barry from "./people/barry";
import people__ben from "./people/ben";
import people__benjieGillam from "./people/benjie-gillam";
import people__bodil from "./people/bodil";
import people__bohdanLiashenko from "./people/bohdan-liashenko";
import people__brent from "./people/brent";
import people__brunoLourenco from "./people/bruno-lourenco";
import people__calin from "./people/calin";
import people__calinb from "./people/calinb";
import people__carolynStransky from "./people/carolyn-stransky";
import people__charlie from "./people/charlie";
import people__christianAlfoni from "./people/christian-alfoni";
import people__christofferNiska from "./people/christoffer-niska";
import people__danSchafer from "./people/dan-schafer";
import people__danielE from "./people/daniel-e";
import people__danielM from "./people/daniel-m";
import people__daniel from "./people/daniel";
import people__dario from "./people/dario";
import people__davidC from "./people/david-c";
import people__davidKhourshid from "./people/david-khourshid";
import people__david from "./people/david";
import people__devlin from "./people/devlin";
import people__diegoHaz from "./people/diego-haz";
import people__dmitriy from "./people/dmitriy";
import people__doug from "./people/doug";
import people__dragos from "./people/dragos";
import people__dustinSchau from "./people/dustin-schau";
import people__eemeliAro from "./people/eemeli-aro";
import people__eevis from "./people/eevis";
import people__eli from "./people/eli";
import people__elisa from "./people/elisa";
import people__ellieDay from "./people/ellie-day";
import people__eloyDuran from "./people/eloy-duran";
import people__emilia from "./people/emilia";
import people__emma from "./people/emma";
import people__emmi from "./people/emmi";
import people__erikRasmussen from "./people/erik-rasmussen";
import people__esaMatti from "./people/esa-matti";
import people__ewa from "./people/ewa";
import people__facundo from "./people/facundo";
import people__farzadYz from "./people/farzad-yz";
import people__federico from "./people/federico";
import people__felix from "./people/felix";
import people__francois from "./people/francois";
import people__gantLaborde from "./people/gant-laborde";
import people__georgeMandis from "./people/george-mandis";
import people__georgios from "./people/georgios";
import people__gleb from "./people/gleb";
import people__glennReyes from "./people/glenn-reyes";
import people__harriMaatta from "./people/harri-maatta";
import people__helenZhukova from "./people/helen-zhukova";
import people__henrik from "./people/henrik";
import people__isaSilveira from "./people/isa-silveira";
import people__ivanGoncharov from "./people/ivan-goncharov";
import people__ivanOrlov from "./people/ivan-orlov";
import people__jamonHolmgren from "./people/jamon-holmgren";
import people__jan from "./people/jan";
import people__janiEvakallio from "./people/jani-evakallio";
import people__janne from "./people/janne";
import people__jaredPalmer from "./people/jared-palmer";
import people__jari from "./people/jari";
import people__jasmin from "./people/jasmin";
import people__jason from "./people/jason";
import people__je from "./people/je";
import people__jec from "./people/jec";
import people__jen from "./people/jen";
import people__jeremyWagner from "./people/jeremy-wagner";
import people__jimmyJia from "./people/jimmy-jia";
import people__jo from "./people/jo";
import people__joe from "./people/joe";
import people__johannesSchickling from "./people/johannes-schickling";
import people__joniNevalainen from "./people/joni-nevalainen";
import people__joonasP from "./people/joonas-p";
import people__joonas from "./people/joonas";
import people__juan from "./people/juan";
import people__juhaLinnanen from "./people/juha-linnanen";
import people__juhani from "./people/juhani";
import people__juhis from "./people/juhis";
import people__juhoLehtinen from "./people/juho-lehtinen";
import people__juhoVepsalainen from "./people/juho-vepsalainen";
import people__julien from "./people/julien";
import people__juri from "./people/juri";
import people__jussi from "./people/jussi";
import people__kadiKraman from "./people/kadi-kraman";
import people__kasiaJastrzebska from "./people/kasia-jastrzebska";
import people__kenWheeler from "./people/ken-wheeler";
import people__kenigboloMeyaStephen from "./people/kenigbolo-meya-stephen";
import people__kennethSutherland from "./people/kenneth-sutherland";
import people__kentCDodds from "./people/kent-c-dodds";
import people__kevin from "./people/kevin";
import people__kirsi from "./people/kirsi";
import people__kristaJantti from "./people/krista-jantti";
import people__kristopher from "./people/kristopher";
import people__krutie from "./people/krutie";
import people__lainey from "./people/lainey";
import people__lauraGonzalez from "./people/laura-gonzalez";
import people__laura from "./people/laura";
import people__laurak from "./people/laurak";
import people__laurao from "./people/laurao";
import people__lauri from "./people/lauri";
import people__liran from "./people/liran";
import people__lucaMatteis from "./people/luca-matteis";
import people__luca from "./people/luca";
import people__lukas from "./people/lukas";
import people__lukeJackson from "./people/luke-jackson";
import people__m4Dz from "./people/m4dz";
import people__maaretPyhajarvi from "./people/maaret-pyhajarvi";
import people__madalyn from "./people/madalyn";
import people__maggie from "./people/maggie";
import people__manjula from "./people/manjula";
import people__manuelMatuzovic from "./people/manuel-matuzovic";
import people__marcAndreGiroux from "./people/marc-andre-giroux";
import people__margarita from "./people/margarita";
import people__marianna from "./people/marianna";
import people__mario from "./people/mario";
import people__mark from "./people/mark";
import people__matias from "./people/matias";
import people__matt from "./people/matt";
import people__matteo from "./people/matteo";
import people__matthewM from "./people/matthew-m";
import people__matthew from "./people/matthew";
import people__max from "./people/max";
import people__michael from "./people/michael";
import people__michalChudziak from "./people/michal-chudziak";
import people__michelWeststrate from "./people/michel-weststrate";
import people__mika from "./people/mika";
import people__mikeBerman from "./people/mike-berman";
import people__mikhailNovikov from "./people/mikhail-novikov";
import people__milecia from "./people/milecia";
import people__misko from "./people/misko";
import people__mo from "./people/mo";
import people__monicaLent from "./people/monica-lent";
import people__naderDabit from "./people/nader-dabit";
import people__naman from "./people/naman";
import people__nasim from "./people/nasim";
import people__nataliaTepluhina from "./people/natalia-tepluhina";
import people__nicola from "./people/nicola";
import people__nidhi from "./people/nidhi";
import people__nikGraf from "./people/nik-graf";
import people__niklas from "./people/niklas";
import people__norbert from "./people/norbert";
import people__nur from "./people/nur";
import people__ohans from "./people/ohans";
import people__olavi from "./people/olavi";
import people__pasi from "./people/pasi";
import people__patrickEcker from "./people/patrick-ecker";
import people__patrickHund from "./people/patrick-hund";
import people__paul from "./people/paul";
import people__pekka from "./people/pekka";
import people__pete from "./people/pete";
import people__rachelNabors from "./people/rachel-nabors";
import people__rami from "./people/rami";
import people__ramona from "./people/ramona";
import people__rashmi from "./people/rashmi";
import people__rebeccaHill from "./people/rebecca-hill";
import people__rickHanlon from "./people/rick-hanlon";
import people__rob from "./people/rob";
import people__roosa from "./people/roosa";
import people__rotemMizrachiMeidan from "./people/rotem-mizrachi-meidan";
import people__ryan from "./people/ryan";
import people__saku from "./people/saku";
import people__salla from "./people/salla";
import people__samuel from "./people/samuel";
import people__samuliHakoniemi from "./people/samuli-hakoniemi";
import people__saraVieira from "./people/sara-vieira";
import people__satu from "./people/satu";
import people__sebastian from "./people/sebastian";
import people__shane from "./people/shane";
import people__shayKeinan from "./people/shay-keinan";
import people__shodipo from "./people/shodipo";
import people__siaKaramalegos from "./people/sia-karamalegos";
import people__stephanie from "./people/stephanie";
import people__steve from "./people/steve";
import people__sunil from "./people/sunil";
import people__svenSauleau from "./people/sven-sauleau";
import people__taelurAlexis from "./people/taelur-alexis";
import people__tanja from "./people/tanja";
import people__tanmaiGopal from "./people/tanmai-gopal";
import people__tejasKumar from "./people/tejas-kumar";
import people__teroParviainen from "./people/tero-parviainen";
import people__thaisSantos from "./people/thais-santos";
import people__thomas from "./people/thomas";
import people__tobiasTimm from "./people/tobias-timm";
import people__tomasKonrady from "./people/tomas-konrady";
import people__toniRistola from "./people/toni-ristola";
import people__tonyEnnis from "./people/tony-ennis";
import people__tonyKovanen from "./people/tony-kovanen";
import people__travis from "./people/travis";
import people__tuuliTiilikainen from "./people/tuuli-tiilikainen";
import people__uj from "./people/uj";
import people__una from "./people/una";
import people__varyaStepanova from "./people/varya-stepanova";
import people__villeImmonen from "./people/ville-immonen";
import people__villePelkonen from "./people/ville-pelkonen";
import people__vismit from "./people/vismit";
import people__vivekNayyar from "./people/vivek-nayyar";
import people__woody from "./people/woody";
import people__xiaoru from "./people/xiaoru";
import people__yan from "./people/yan";
import people__yang from "./people/yang";
import people__yoav from "./people/yoav";
import people__yulia from "./people/yulia";
import people__zak from "./people/zak";

export const people = {
  aapeli: people__aapeli,
  aarniKoskela: people__aarniKoskela,
  adamMiskiewicz: people__adamMiskiewicz,
  aleksandra: people__aleksandra,
  aleksiPousar: people__aleksiPousar,
  alexBooker: people__alexBooker,
  anastasiia: people__anastasiia,
  andreas: people__andreas,
  andrei: people__andrei,
  andrewRhyne: people__andrewRhyne,
  andreyG: people__andreyG,
  andreyOkonetchnikov: people__andreyOkonetchnikov,
  annaDoubkova: people__annaDoubkova,
  ante: people__ante,
  artemSapegin: people__artemSapegin,
  artemZakharchenko: people__artemZakharchenko,
  aurora: people__aurora,
  barry: people__barry,
  ben: people__ben,
  benjieGillam: people__benjieGillam,
  bodil: people__bodil,
  bohdanLiashenko: people__bohdanLiashenko,
  brent: people__brent,
  brunoLourenco: people__brunoLourenco,
  calin: people__calin,
  calinb: people__calinb,
  carolynStransky: people__carolynStransky,
  charlie: people__charlie,
  christianAlfoni: people__christianAlfoni,
  christofferNiska: people__christofferNiska,
  danSchafer: people__danSchafer,
  danielE: people__danielE,
  danielM: people__danielM,
  daniel: people__daniel,
  dario: people__dario,
  davidC: people__davidC,
  davidKhourshid: people__davidKhourshid,
  david: people__david,
  devlin: people__devlin,
  diegoHaz: people__diegoHaz,
  dmitriy: people__dmitriy,
  doug: people__doug,
  dragos: people__dragos,
  dustinSchau: people__dustinSchau,
  eemeliAro: people__eemeliAro,
  eevis: people__eevis,
  eli: people__eli,
  elisa: people__elisa,
  ellieDay: people__ellieDay,
  eloyDuran: people__eloyDuran,
  emilia: people__emilia,
  emma: people__emma,
  emmi: people__emmi,
  erikRasmussen: people__erikRasmussen,
  esaMatti: people__esaMatti,
  ewa: people__ewa,
  facundo: people__facundo,
  farzadYz: people__farzadYz,
  federico: people__federico,
  felix: people__felix,
  francois: people__francois,
  gantLaborde: people__gantLaborde,
  georgeMandis: people__georgeMandis,
  georgios: people__georgios,
  gleb: people__gleb,
  glennReyes: people__glennReyes,
  harriMaatta: people__harriMaatta,
  helenZhukova: people__helenZhukova,
  henrik: people__henrik,
  isaSilveira: people__isaSilveira,
  ivanGoncharov: people__ivanGoncharov,
  ivanOrlov: people__ivanOrlov,
  jamonHolmgren: people__jamonHolmgren,
  jan: people__jan,
  janiEvakallio: people__janiEvakallio,
  janne: people__janne,
  jaredPalmer: people__jaredPalmer,
  jari: people__jari,
  jasmin: people__jasmin,
  jason: people__jason,
  je: people__je,
  jec: people__jec,
  jen: people__jen,
  jeremyWagner: people__jeremyWagner,
  jimmyJia: people__jimmyJia,
  jo: people__jo,
  joe: people__joe,
  johannesSchickling: people__johannesSchickling,
  joniNevalainen: people__joniNevalainen,
  joonasP: people__joonasP,
  joonas: people__joonas,
  juan: people__juan,
  juhaLinnanen: people__juhaLinnanen,
  juhani: people__juhani,
  juhis: people__juhis,
  juhoLehtinen: people__juhoLehtinen,
  juhoVepsalainen: people__juhoVepsalainen,
  julien: people__julien,
  juri: people__juri,
  jussi: people__jussi,
  kadiKraman: people__kadiKraman,
  kasiaJastrzebska: people__kasiaJastrzebska,
  kenWheeler: people__kenWheeler,
  kenigboloMeyaStephen: people__kenigboloMeyaStephen,
  kennethSutherland: people__kennethSutherland,
  kentCDodds: people__kentCDodds,
  kevin: people__kevin,
  kirsi: people__kirsi,
  kristaJantti: people__kristaJantti,
  kristopher: people__kristopher,
  krutie: people__krutie,
  lainey: people__lainey,
  lauraGonzalez: people__lauraGonzalez,
  laura: people__laura,
  laurak: people__laurak,
  laurao: people__laurao,
  lauri: people__lauri,
  liran: people__liran,
  lucaMatteis: people__lucaMatteis,
  luca: people__luca,
  lukas: people__lukas,
  lukeJackson: people__lukeJackson,
  m4Dz: people__m4Dz,
  maaretPyhajarvi: people__maaretPyhajarvi,
  madalyn: people__madalyn,
  maggie: people__maggie,
  manjula: people__manjula,
  manuelMatuzovic: people__manuelMatuzovic,
  marcAndreGiroux: people__marcAndreGiroux,
  margarita: people__margarita,
  marianna: people__marianna,
  mario: people__mario,
  mark: people__mark,
  matias: people__matias,
  matt: people__matt,
  matteo: people__matteo,
  matthewM: people__matthewM,
  matthew: people__matthew,
  max: people__max,
  michael: people__michael,
  michalChudziak: people__michalChudziak,
  michelWeststrate: people__michelWeststrate,
  mika: people__mika,
  mikeBerman: people__mikeBerman,
  mikhailNovikov: people__mikhailNovikov,
  milecia: people__milecia,
  misko: people__misko,
  mo: people__mo,
  monicaLent: people__monicaLent,
  naderDabit: people__naderDabit,
  naman: people__naman,
  nasim: people__nasim,
  nataliaTepluhina: people__nataliaTepluhina,
  nicola: people__nicola,
  nidhi: people__nidhi,
  nikGraf: people__nikGraf,
  niklas: people__niklas,
  norbert: people__norbert,
  nur: people__nur,
  ohans: people__ohans,
  olavi: people__olavi,
  pasi: people__pasi,
  patrickEcker: people__patrickEcker,
  patrickHund: people__patrickHund,
  paul: people__paul,
  pekka: people__pekka,
  pete: people__pete,
  rachelNabors: people__rachelNabors,
  rami: people__rami,
  ramona: people__ramona,
  rashmi: people__rashmi,
  rebeccaHill: people__rebeccaHill,
  rickHanlon: people__rickHanlon,
  rob: people__rob,
  roosa: people__roosa,
  rotemMizrachiMeidan: people__rotemMizrachiMeidan,
  ryan: people__ryan,
  saku: people__saku,
  salla: people__salla,
  samuel: people__samuel,
  samuliHakoniemi: people__samuliHakoniemi,
  saraVieira: people__saraVieira,
  satu: people__satu,
  sebastian: people__sebastian,
  shane: people__shane,
  shayKeinan: people__shayKeinan,
  shodipo: people__shodipo,
  siaKaramalegos: people__siaKaramalegos,
  stephanie: people__stephanie,
  steve: people__steve,
  sunil: people__sunil,
  svenSauleau: people__svenSauleau,
  taelurAlexis: people__taelurAlexis,
  tanja: people__tanja,
  tanmaiGopal: people__tanmaiGopal,
  tejasKumar: people__tejasKumar,
  teroParviainen: people__teroParviainen,
  thaisSantos: people__thaisSantos,
  thomas: people__thomas,
  tobiasTimm: people__tobiasTimm,
  tomasKonrady: people__tomasKonrady,
  toniRistola: people__toniRistola,
  tonyEnnis: people__tonyEnnis,
  tonyKovanen: people__tonyKovanen,
  travis: people__travis,
  tuuliTiilikainen: people__tuuliTiilikainen,
  uj: people__uj,
  una: people__una,
  varyaStepanova: people__varyaStepanova,
  villeImmonen: people__villeImmonen,
  villePelkonen: people__villePelkonen,
  vismit: people__vismit,
  vivekNayyar: people__vivekNayyar,
  woody: people__woody,
  xiaoru: people__xiaoru,
  yan: people__yan,
  yang: people__yang,
  yoav: people__yoav,
  yulia: people__yulia,
  zak: people__zak,
} as const;

export const aapeli = people.aapeli;
export const aarniKoskela = people.aarniKoskela;
export const adamMiskiewicz = people.adamMiskiewicz;
export const aleksandra = people.aleksandra;
export const aleksiPousar = people.aleksiPousar;
export const alexBooker = people.alexBooker;
export const anastasiia = people.anastasiia;
export const andreas = people.andreas;
export const andrei = people.andrei;
export const andrewRhyne = people.andrewRhyne;
export const andreyG = people.andreyG;
export const andreyOkonetchnikov = people.andreyOkonetchnikov;
export const annaDoubkova = people.annaDoubkova;
export const ante = people.ante;
export const artemSapegin = people.artemSapegin;
export const artemZakharchenko = people.artemZakharchenko;
export const aurora = people.aurora;
export const barry = people.barry;
export const ben = people.ben;
export const benjieGillam = people.benjieGillam;
export const bodil = people.bodil;
export const bohdanLiashenko = people.bohdanLiashenko;
export const brent = people.brent;
export const brunoLourenco = people.brunoLourenco;
export const calin = people.calin;
export const calinb = people.calinb;
export const carolynStransky = people.carolynStransky;
export const charlie = people.charlie;
export const christianAlfoni = people.christianAlfoni;
export const christofferNiska = people.christofferNiska;
export const danSchafer = people.danSchafer;
export const danielE = people.danielE;
export const danielM = people.danielM;
export const daniel = people.daniel;
export const dario = people.dario;
export const davidC = people.davidC;
export const davidKhourshid = people.davidKhourshid;
export const david = people.david;
export const devlin = people.devlin;
export const diegoHaz = people.diegoHaz;
export const dmitriy = people.dmitriy;
export const doug = people.doug;
export const dragos = people.dragos;
export const dustinSchau = people.dustinSchau;
export const eemeliAro = people.eemeliAro;
export const eevis = people.eevis;
export const eli = people.eli;
export const elisa = people.elisa;
export const ellieDay = people.ellieDay;
export const eloyDuran = people.eloyDuran;
export const emilia = people.emilia;
export const emma = people.emma;
export const emmi = people.emmi;
export const erikRasmussen = people.erikRasmussen;
export const esaMatti = people.esaMatti;
export const ewa = people.ewa;
export const facundo = people.facundo;
export const farzadYz = people.farzadYz;
export const federico = people.federico;
export const felix = people.felix;
export const francois = people.francois;
export const gantLaborde = people.gantLaborde;
export const georgeMandis = people.georgeMandis;
export const georgios = people.georgios;
export const gleb = people.gleb;
export const glennReyes = people.glennReyes;
export const harriMaatta = people.harriMaatta;
export const helenZhukova = people.helenZhukova;
export const henrik = people.henrik;
export const isaSilveira = people.isaSilveira;
export const ivanGoncharov = people.ivanGoncharov;
export const ivanOrlov = people.ivanOrlov;
export const jamonHolmgren = people.jamonHolmgren;
export const jan = people.jan;
export const janiEvakallio = people.janiEvakallio;
export const janne = people.janne;
export const jaredPalmer = people.jaredPalmer;
export const jari = people.jari;
export const jasmin = people.jasmin;
export const jason = people.jason;
export const je = people.je;
export const jec = people.jec;
export const jen = people.jen;
export const jeremyWagner = people.jeremyWagner;
export const jimmyJia = people.jimmyJia;
export const jo = people.jo;
export const joe = people.joe;
export const johannesSchickling = people.johannesSchickling;
export const joniNevalainen = people.joniNevalainen;
export const joonasP = people.joonasP;
export const joonas = people.joonas;
export const juan = people.juan;
export const juhaLinnanen = people.juhaLinnanen;
export const juhani = people.juhani;
export const juhis = people.juhis;
export const juhoLehtinen = people.juhoLehtinen;
export const juhoVepsalainen = people.juhoVepsalainen;
export const julien = people.julien;
export const juri = people.juri;
export const jussi = people.jussi;
export const kadiKraman = people.kadiKraman;
export const kasiaJastrzebska = people.kasiaJastrzebska;
export const kenWheeler = people.kenWheeler;
export const kenigboloMeyaStephen = people.kenigboloMeyaStephen;
export const kennethSutherland = people.kennethSutherland;
export const kentCDodds = people.kentCDodds;
export const kevin = people.kevin;
export const kirsi = people.kirsi;
export const kristaJantti = people.kristaJantti;
export const kristopher = people.kristopher;
export const krutie = people.krutie;
export const lainey = people.lainey;
export const lauraGonzalez = people.lauraGonzalez;
export const laura = people.laura;
export const laurak = people.laurak;
export const laurao = people.laurao;
export const lauri = people.lauri;
export const liran = people.liran;
export const lucaMatteis = people.lucaMatteis;
export const luca = people.luca;
export const lukas = people.lukas;
export const lukeJackson = people.lukeJackson;
export const m4Dz = people.m4Dz;
export const maaretPyhajarvi = people.maaretPyhajarvi;
export const madalyn = people.madalyn;
export const maggie = people.maggie;
export const manjula = people.manjula;
export const manuelMatuzovic = people.manuelMatuzovic;
export const marcAndreGiroux = people.marcAndreGiroux;
export const margarita = people.margarita;
export const marianna = people.marianna;
export const mario = people.mario;
export const mark = people.mark;
export const matias = people.matias;
export const matt = people.matt;
export const matteo = people.matteo;
export const matthewM = people.matthewM;
export const matthew = people.matthew;
export const max = people.max;
export const michael = people.michael;
export const michalChudziak = people.michalChudziak;
export const michelWeststrate = people.michelWeststrate;
export const mika = people.mika;
export const mikeBerman = people.mikeBerman;
export const mikhailNovikov = people.mikhailNovikov;
export const milecia = people.milecia;
export const misko = people.misko;
export const mo = people.mo;
export const monicaLent = people.monicaLent;
export const naderDabit = people.naderDabit;
export const naman = people.naman;
export const nasim = people.nasim;
export const nataliaTepluhina = people.nataliaTepluhina;
export const nicola = people.nicola;
export const nidhi = people.nidhi;
export const nikGraf = people.nikGraf;
export const niklas = people.niklas;
export const norbert = people.norbert;
export const nur = people.nur;
export const ohans = people.ohans;
export const olavi = people.olavi;
export const pasi = people.pasi;
export const patrickEcker = people.patrickEcker;
export const patrickHund = people.patrickHund;
export const paul = people.paul;
export const pekka = people.pekka;
export const pete = people.pete;
export const rachelNabors = people.rachelNabors;
export const rami = people.rami;
export const ramona = people.ramona;
export const rashmi = people.rashmi;
export const rebeccaHill = people.rebeccaHill;
export const rickHanlon = people.rickHanlon;
export const rob = people.rob;
export const roosa = people.roosa;
export const rotemMizrachiMeidan = people.rotemMizrachiMeidan;
export const ryan = people.ryan;
export const saku = people.saku;
export const salla = people.salla;
export const samuel = people.samuel;
export const samuliHakoniemi = people.samuliHakoniemi;
export const saraVieira = people.saraVieira;
export const satu = people.satu;
export const sebastian = people.sebastian;
export const shane = people.shane;
export const shayKeinan = people.shayKeinan;
export const shodipo = people.shodipo;
export const siaKaramalegos = people.siaKaramalegos;
export const stephanie = people.stephanie;
export const steve = people.steve;
export const sunil = people.sunil;
export const svenSauleau = people.svenSauleau;
export const taelurAlexis = people.taelurAlexis;
export const tanja = people.tanja;
export const tanmaiGopal = people.tanmaiGopal;
export const tejasKumar = people.tejasKumar;
export const teroParviainen = people.teroParviainen;
export const thaisSantos = people.thaisSantos;
export const thomas = people.thomas;
export const tobiasTimm = people.tobiasTimm;
export const tomasKonrady = people.tomasKonrady;
export const toniRistola = people.toniRistola;
export const tonyEnnis = people.tonyEnnis;
export const tonyKovanen = people.tonyKovanen;
export const travis = people.travis;
export const tuuliTiilikainen = people.tuuliTiilikainen;
export const uj = people.uj;
export const una = people.una;
export const varyaStepanova = people.varyaStepanova;
export const villeImmonen = people.villeImmonen;
export const villePelkonen = people.villePelkonen;
export const vismit = people.vismit;
export const vivekNayyar = people.vivekNayyar;
export const woody = people.woody;
export const xiaoru = people.xiaoru;
export const yan = people.yan;
export const yang = people.yang;
export const yoav = people.yoav;
export const yulia = people.yulia;
export const zak = people.zak;

import sponsors__a11Yclub from "./sponsors/a11yclub";
import sponsors__agentconf from "./sponsors/agentconf";
import sponsors__alma from "./sponsors/alma";
import sponsors__amazon from "./sponsors/amazon";
import sponsors__apidays from "./sponsors/apidays";
import sponsors__apiops from "./sponsors/apiops";
import sponsors__apollo from "./sponsors/apollo";
import sponsors__backscreen from "./sponsors/backscreen";
import sponsors__bangalore from "./sponsors/bangalore";
import sponsors__bejs from "./sponsors/bejs";
import sponsors__brella from "./sponsors/brella";
import sponsors__cai from "./sponsors/cai";
import sponsors__codento from "./sponsors/codento";
import sponsors__columbiaroad from "./sponsors/columbiaroad";
import sponsors__cybercom from "./sponsors/cybercom";
import sponsors__designsystemslondon from "./sponsors/designsystemslondon";
import sponsors__digia from "./sponsors/digia";
import sponsors__digitalExpert from "./sponsors/digital-expert";
import sponsors__divriots from "./sponsors/divriots";
import sponsors__dna325 from "./sponsors/dna325";
import sponsors__dojs from "./sponsors/dojs";
import sponsors__dynatrace from "./sponsors/dynatrace";
import sponsors__elisa from "./sponsors/elisa";
import sponsors__evitec from "./sponsors/evitec";
import sponsors__fb from "./sponsors/fb";
import sponsors__formidable from "./sponsors/formidable";
import sponsors__frankenjs from "./sponsors/frankenjs";
import sponsors__friikit from "./sponsors/friikit";
import sponsors__futurice from "./sponsors/futurice";
import sponsors__gatsby from "./sponsors/gatsby";
import sponsors__geekle from "./sponsors/geekle";
import sponsors__geniem from "./sponsors/geniem";
import sponsors__ginetta from "./sponsors/ginetta";
import sponsors__glorium from "./sponsors/glorium";
import sponsors__gofore from "./sponsors/gofore";
import sponsors__gqlhongkong from "./sponsors/gqlhongkong";
import sponsors__graphqlFinland from "./sponsors/graphql-finland";
import sponsors__grusp from "./sponsors/grusp";
import sponsors__haagahelia from "./sponsors/haagahelia";
import sponsors__halfstack from "./sponsors/halfstack";
import sponsors__hasura from "./sponsors/hasura";
import sponsors__hbc from "./sponsors/hbc";
import sponsors__honeypot from "./sponsors/honeypot";
import sponsors__huuva from "./sponsors/huuva";
import sponsors__jscamp from "./sponsors/jscamp";
import sponsors__jsconfbp from "./sponsors/jsconfbp";
import sponsors__jsday from "./sponsors/jsday";
import sponsors__jskongress from "./sponsors/jskongress";
import sponsors__jsn from "./sponsors/jsn";
import sponsors__knowit from "./sponsors/knowit";
import sponsors__kongres from "./sponsors/kongres";
import sponsors__koodiasuomesta from "./sponsors/koodiasuomesta";
import sponsors__loihdefactor from "./sponsors/loihdefactor";
import sponsors__mastra from "./sponsors/mastra";
import sponsors__meiko from "./sponsors/meiko";
import sponsors__monolisa from "./sponsors/monolisa";
import sponsors__moonhighway from "./sponsors/moonhighway";
import sponsors__motley from "./sponsors/motley";
import sponsors__netum from "./sponsors/netum";
import sponsors__nightingale from "./sponsors/nightingale";
import sponsors__nitor from "./sponsors/nitor";
import sponsors__nodecongress from "./sponsors/nodecongress";
import sponsors__ohjelmistofriikit from "./sponsors/ohjelmistofriikit";
import sponsors__osaango from "./sponsors/osaango";
import sponsors__postgraphile from "./sponsors/postgraphile";
import sponsors__prisma from "./sponsors/prisma";
import sponsors__quentic from "./sponsors/quentic";
import sponsors__reactFinland from "./sponsors/react-finland";
import sponsors__reactalicante from "./sponsors/reactalicante";
import sponsors__reactbrussels from "./sponsors/reactbrussels";
import sponsors__reactdayberlin from "./sponsors/reactdayberlin";
import sponsors__reactfest from "./sponsors/reactfest";
import sponsors__reactindia from "./sponsors/reactindia";
import sponsors__reactjsday from "./sponsors/reactjsday";
import sponsors__reactjsgirls from "./sponsors/reactjsgirls";
import sponsors__reactnativeeu from "./sponsors/reactnativeeu";
import sponsors__reactnewyork from "./sponsors/reactnewyork";
import sponsors__reactnorway from "./sponsors/reactnorway";
import sponsors__reactparis from "./sponsors/reactparis";
import sponsors__reactsummit from "./sponsors/reactsummit";
import sponsors__reactweek from "./sponsors/reactweek";
import sponsors__reaktor from "./sponsors/reaktor";
import sponsors__reasonconf from "./sponsors/reasonconf";
import sponsors__relex from "./sponsors/relex";
import sponsors__rlc from "./sponsors/rlc";
import sponsors__rohea from "./sponsors/rohea";
import sponsors__rp from "./sponsors/rp";
import sponsors__sae from "./sponsors/sae";
import sponsors__smartly from "./sponsors/smartly";
import sponsors__solita from "./sponsors/solita";
import sponsors__stickermule from "./sponsors/stickermule";
import sponsors__supermetrics from "./sponsors/supermetrics";
import sponsors__survivejs from "./sponsors/survivejs";
import sponsors__techEvents from "./sponsors/tech-events";
import sponsors__toddle from "./sponsors/toddle";
import sponsors__toska from "./sponsors/toska";
import sponsors__twir from "./sponsors/twir";
import sponsors__typeof from "./sponsors/typeof";
import sponsors__upcloud from "./sponsors/upcloud";
import sponsors__utopia from "./sponsors/utopia";
import sponsors__valamis from "./sponsors/valamis";
import sponsors__verkkokauppa from "./sponsors/verkkokauppa";
import sponsors__vihat from "./sponsors/vihat";
import sponsors__vincit from "./sponsors/vincit";
import sponsors__webexpo from "./sponsors/webexpo";
import sponsors__wonna from "./sponsors/wonna";
import sponsors__wunder from "./sponsors/wunder";
import sponsors__wunderdog from "./sponsors/wunderdog";
import sponsors__yglfkyiv from "./sponsors/yglfkyiv";
import sponsors__yle from "./sponsors/yle";
import sponsors__zapier from "./sponsors/zapier";
import sponsors__zeroplusx from "./sponsors/zeroplusx";
import sponsors__zurichjs from "./sponsors/zurichjs";

export const sponsors = {
  a11Yclub: sponsors__a11Yclub,
  agentconf: sponsors__agentconf,
  alma: sponsors__alma,
  amazon: sponsors__amazon,
  apidays: sponsors__apidays,
  apiops: sponsors__apiops,
  apollo: sponsors__apollo,
  backscreen: sponsors__backscreen,
  bangalore: sponsors__bangalore,
  bejs: sponsors__bejs,
  brella: sponsors__brella,
  cai: sponsors__cai,
  codento: sponsors__codento,
  columbiaroad: sponsors__columbiaroad,
  cybercom: sponsors__cybercom,
  designsystemslondon: sponsors__designsystemslondon,
  digia: sponsors__digia,
  digitalExpert: sponsors__digitalExpert,
  divriots: sponsors__divriots,
  dna325: sponsors__dna325,
  dojs: sponsors__dojs,
  dynatrace: sponsors__dynatrace,
  elisa: sponsors__elisa,
  evitec: sponsors__evitec,
  fb: sponsors__fb,
  formidable: sponsors__formidable,
  frankenjs: sponsors__frankenjs,
  friikit: sponsors__friikit,
  futurice: sponsors__futurice,
  gatsby: sponsors__gatsby,
  geekle: sponsors__geekle,
  geniem: sponsors__geniem,
  ginetta: sponsors__ginetta,
  glorium: sponsors__glorium,
  gofore: sponsors__gofore,
  gqlhongkong: sponsors__gqlhongkong,
  graphqlFinland: sponsors__graphqlFinland,
  grusp: sponsors__grusp,
  haagahelia: sponsors__haagahelia,
  halfstack: sponsors__halfstack,
  hasura: sponsors__hasura,
  hbc: sponsors__hbc,
  honeypot: sponsors__honeypot,
  huuva: sponsors__huuva,
  jscamp: sponsors__jscamp,
  jsconfbp: sponsors__jsconfbp,
  jsday: sponsors__jsday,
  jskongress: sponsors__jskongress,
  jsn: sponsors__jsn,
  knowit: sponsors__knowit,
  kongres: sponsors__kongres,
  koodiasuomesta: sponsors__koodiasuomesta,
  loihdefactor: sponsors__loihdefactor,
  mastra: sponsors__mastra,
  meiko: sponsors__meiko,
  monolisa: sponsors__monolisa,
  moonhighway: sponsors__moonhighway,
  motley: sponsors__motley,
  netum: sponsors__netum,
  nightingale: sponsors__nightingale,
  nitor: sponsors__nitor,
  nodecongress: sponsors__nodecongress,
  ohjelmistofriikit: sponsors__ohjelmistofriikit,
  osaango: sponsors__osaango,
  postgraphile: sponsors__postgraphile,
  prisma: sponsors__prisma,
  quentic: sponsors__quentic,
  reactFinland: sponsors__reactFinland,
  reactalicante: sponsors__reactalicante,
  reactbrussels: sponsors__reactbrussels,
  reactdayberlin: sponsors__reactdayberlin,
  reactfest: sponsors__reactfest,
  reactindia: sponsors__reactindia,
  reactjsday: sponsors__reactjsday,
  reactjsgirls: sponsors__reactjsgirls,
  reactnativeeu: sponsors__reactnativeeu,
  reactnewyork: sponsors__reactnewyork,
  reactnorway: sponsors__reactnorway,
  reactparis: sponsors__reactparis,
  reactsummit: sponsors__reactsummit,
  reactweek: sponsors__reactweek,
  reaktor: sponsors__reaktor,
  reasonconf: sponsors__reasonconf,
  relex: sponsors__relex,
  rlc: sponsors__rlc,
  rohea: sponsors__rohea,
  rp: sponsors__rp,
  sae: sponsors__sae,
  smartly: sponsors__smartly,
  solita: sponsors__solita,
  stickermule: sponsors__stickermule,
  supermetrics: sponsors__supermetrics,
  survivejs: sponsors__survivejs,
  techEvents: sponsors__techEvents,
  toddle: sponsors__toddle,
  toska: sponsors__toska,
  twir: sponsors__twir,
  typeof: sponsors__typeof,
  upcloud: sponsors__upcloud,
  utopia: sponsors__utopia,
  valamis: sponsors__valamis,
  verkkokauppa: sponsors__verkkokauppa,
  vihat: sponsors__vihat,
  vincit: sponsors__vincit,
  webexpo: sponsors__webexpo,
  wonna: sponsors__wonna,
  wunder: sponsors__wunder,
  wunderdog: sponsors__wunderdog,
  yglfkyiv: sponsors__yglfkyiv,
  yle: sponsors__yle,
  zapier: sponsors__zapier,
  zeroplusx: sponsors__zeroplusx,
  zurichjs: sponsors__zurichjs,
} as const;
