// This file is generated by `npm run generate:indices`.
// Do not edit it manually.

export * from "./generated-core";


import freezingEdge2020Talks__bodil from "./freezing-edge-2020/talks/bodil";
import freezingEdge2020Talks__georgeMandis from "./freezing-edge-2020/talks/george-mandis";
import freezingEdge2020Talks__kenWheeler from "./freezing-edge-2020/talks/ken-wheeler";
import freezingEdge2020Talks__kristaJantti from "./freezing-edge-2020/talks/krista-jantti";
import freezingEdge2020Talks__nataliaTepluhina from "./freezing-edge-2020/talks/natalia-tepluhina";
import freezingEdge2020Talks__patrickStapfer from "./freezing-edge-2020/talks/patrick-stapfer";
import freezingEdge2020Talks__teroParviainen from "./freezing-edge-2020/talks/tero-parviainen";

export const freezingEdge2020Talks = {
  bodil: freezingEdge2020Talks__bodil,
  georgeMandis: freezingEdge2020Talks__georgeMandis,
  kenWheeler: freezingEdge2020Talks__kenWheeler,
  kristaJantti: freezingEdge2020Talks__kristaJantti,
  nataliaTepluhina: freezingEdge2020Talks__nataliaTepluhina,
  patrickStapfer: freezingEdge2020Talks__patrickStapfer,
  teroParviainen: freezingEdge2020Talks__teroParviainen,
} as const;

import graphqlFinland2018Talks__adamMiskiewicz from "./graphql-finland-2018/talks/adam-miskiewicz";
import graphqlFinland2018Talks__andrewRhyne from "./graphql-finland-2018/talks/andrew-rhyne";
import graphqlFinland2018Talks__benjieGillam from "./graphql-finland-2018/talks/benjie-gillam";
import graphqlFinland2018Talks__carolynStransky from "./graphql-finland-2018/talks/carolyn-stransky";
import graphqlFinland2018Talks__christofferNiska from "./graphql-finland-2018/talks/christoffer-niska";
import graphqlFinland2018Talks__danSchafer from "./graphql-finland-2018/talks/dan-schafer";
import graphqlFinland2018Talks__ellieDay from "./graphql-finland-2018/talks/ellie-day";
import graphqlFinland2018Talks__eloyDuran from "./graphql-finland-2018/talks/eloy-duran";
import graphqlFinland2018Talks__glennReyes from "./graphql-finland-2018/talks/glenn-reyes";
import graphqlFinland2018Talks__helenZhukova from "./graphql-finland-2018/talks/helen-zhukova";
import graphqlFinland2018Talks__ivanGoncharov from "./graphql-finland-2018/talks/ivan-goncharov";
import graphqlFinland2018Talks__jimmyJia from "./graphql-finland-2018/talks/jimmy-jia";
import graphqlFinland2018Talks__johannesSchickling from "./graphql-finland-2018/talks/johannes-schickling";
import graphqlFinland2018Talks__kadiKraman from "./graphql-finland-2018/talks/kadi-kraman";
import graphqlFinland2018Talks__nikGraf from "./graphql-finland-2018/talks/nik-graf";
import graphqlFinland2018Talks__tanmaiGopal from "./graphql-finland-2018/talks/tanmai-gopal";

export const graphqlFinland2018Talks = {
  adamMiskiewicz: graphqlFinland2018Talks__adamMiskiewicz,
  andrewRhyne: graphqlFinland2018Talks__andrewRhyne,
  benjieGillam: graphqlFinland2018Talks__benjieGillam,
  carolynStransky: graphqlFinland2018Talks__carolynStransky,
  christofferNiska: graphqlFinland2018Talks__christofferNiska,
  danSchafer: graphqlFinland2018Talks__danSchafer,
  ellieDay: graphqlFinland2018Talks__ellieDay,
  eloyDuran: graphqlFinland2018Talks__eloyDuran,
  glennReyes: graphqlFinland2018Talks__glennReyes,
  helenZhukova: graphqlFinland2018Talks__helenZhukova,
  ivanGoncharov: graphqlFinland2018Talks__ivanGoncharov,
  jimmyJia: graphqlFinland2018Talks__jimmyJia,
  johannesSchickling: graphqlFinland2018Talks__johannesSchickling,
  kadiKraman: graphqlFinland2018Talks__kadiKraman,
  nikGraf: graphqlFinland2018Talks__nikGraf,
  tanmaiGopal: graphqlFinland2018Talks__tanmaiGopal,
} as const;

import graphqlFinland2018Workshops__juhoWorkshop from "./graphql-finland-2018/workshops/juho-workshop";
import graphqlFinland2018Workshops__marcWorkshop from "./graphql-finland-2018/workshops/marc-workshop";
import graphqlFinland2018Workshops__mikhailWorkshop from "./graphql-finland-2018/workshops/mikhail-workshop";
import graphqlFinland2018Workshops__nikWorkshop from "./graphql-finland-2018/workshops/nik-workshop";

export const graphqlFinland2018Workshops = {
  juhoWorkshop: graphqlFinland2018Workshops__juhoWorkshop,
  marcWorkshop: graphqlFinland2018Workshops__marcWorkshop,
  mikhailWorkshop: graphqlFinland2018Workshops__mikhailWorkshop,
  nikWorkshop: graphqlFinland2018Workshops__nikWorkshop,
} as const;

import reactFinland2018Talks__andreyOkonetchnikov from "./react-finland-2018/talks/andrey-okonetchnikov";
import reactFinland2018Talks__christianAlfoni from "./react-finland-2018/talks/christian-alfoni";
import reactFinland2018Talks__davidKhourshid from "./react-finland-2018/talks/david-khourshid";
import reactFinland2018Talks__eemeliAro2 from "./react-finland-2018/talks/eemeli-aro-2";
import reactFinland2018Talks__eemeliAro from "./react-finland-2018/talks/eemeli-aro";
import reactFinland2018Talks__gantLaborde from "./react-finland-2018/talks/gant-laborde";
import reactFinland2018Talks__janiEvakallio from "./react-finland-2018/talks/jani-evakallio";
import reactFinland2018Talks__juhoVepsalainen from "./react-finland-2018/talks/juho-vepsalainen";
import reactFinland2018Talks__kasiaJastrzebska from "./react-finland-2018/talks/kasia-jastrzebska";
import reactFinland2018Talks__kenWheeler from "./react-finland-2018/talks/ken-wheeler";
import reactFinland2018Talks__michalChudziak from "./react-finland-2018/talks/michal-chudziak";
import reactFinland2018Talks__michelWeststrate from "./react-finland-2018/talks/michel-weststrate";
import reactFinland2018Talks__nikGraf from "./react-finland-2018/talks/nik-graf";
import reactFinland2018Talks__patrickHund from "./react-finland-2018/talks/patrick-hund";
import reactFinland2018Talks__patrickStapfer from "./react-finland-2018/talks/patrick-stapfer";
import reactFinland2018Talks__rotemMizrachiMeidan from "./react-finland-2018/talks/rotem-mizrachi-meidan";
import reactFinland2018Talks__saraVieira from "./react-finland-2018/talks/sara-vieira";
import reactFinland2018Talks__shayKeinan from "./react-finland-2018/talks/shay-keinan";
import reactFinland2018Talks__siaKaramalegos from "./react-finland-2018/talks/sia-karamalegos";
import reactFinland2018Talks__svenSauleau from "./react-finland-2018/talks/sven-sauleau";
import reactFinland2018Talks__toniRistola from "./react-finland-2018/talks/toni-ristola";
import reactFinland2018Talks__varyaStepanova from "./react-finland-2018/talks/varya-stepanova";

export const reactFinland2018Talks = {
  andreyOkonetchnikov: reactFinland2018Talks__andreyOkonetchnikov,
  christianAlfoni: reactFinland2018Talks__christianAlfoni,
  davidKhourshid: reactFinland2018Talks__davidKhourshid,
  eemeliAro2: reactFinland2018Talks__eemeliAro2,
  eemeliAro: reactFinland2018Talks__eemeliAro,
  gantLaborde: reactFinland2018Talks__gantLaborde,
  janiEvakallio: reactFinland2018Talks__janiEvakallio,
  juhoVepsalainen: reactFinland2018Talks__juhoVepsalainen,
  kasiaJastrzebska: reactFinland2018Talks__kasiaJastrzebska,
  kenWheeler: reactFinland2018Talks__kenWheeler,
  michalChudziak: reactFinland2018Talks__michalChudziak,
  michelWeststrate: reactFinland2018Talks__michelWeststrate,
  nikGraf: reactFinland2018Talks__nikGraf,
  patrickHund: reactFinland2018Talks__patrickHund,
  patrickStapfer: reactFinland2018Talks__patrickStapfer,
  rotemMizrachiMeidan: reactFinland2018Talks__rotemMizrachiMeidan,
  saraVieira: reactFinland2018Talks__saraVieira,
  shayKeinan: reactFinland2018Talks__shayKeinan,
  siaKaramalegos: reactFinland2018Talks__siaKaramalegos,
  svenSauleau: reactFinland2018Talks__svenSauleau,
  toniRistola: reactFinland2018Talks__toniRistola,
  varyaStepanova: reactFinland2018Talks__varyaStepanova,
} as const;

import reactFinland2018Workshops__andreyAndArtemWorkshop from "./react-finland-2018/workshops/andrey-and-artem-workshop";
import reactFinland2018Workshops__davidKhourshidWorkshop from "./react-finland-2018/workshops/david-khourshid-workshop";
import reactFinland2018Workshops__gantLabordeWorkshop from "./react-finland-2018/workshops/gant-laborde-workshop";
import reactFinland2018Workshops__juhoVepsalainenWorkshop from "./react-finland-2018/workshops/juho-vepsalainen-workshop";
import reactFinland2018Workshops__michelWeststrateWorkshop from "./react-finland-2018/workshops/michel-weststrate-workshop";
import reactFinland2018Workshops__patrickAndNikWorkshop from "./react-finland-2018/workshops/patrick-and-nik-workshop";
import reactFinland2018Workshops__rotemMizrachiMeidanWorkshop from "./react-finland-2018/workshops/rotem-mizrachi-meidan-workshop";
import reactFinland2018Workshops__saraVieiraWorkshop from "./react-finland-2018/workshops/sara-vieira-workshop";
import reactFinland2018Workshops__siaKaramalegosWorkshop from "./react-finland-2018/workshops/sia-karamalegos-workshop";
import reactFinland2018Workshops__svenSauleauWorkshop from "./react-finland-2018/workshops/sven-sauleau-workshop";

export const reactFinland2018Workshops = {
  andreyAndArtemWorkshop: reactFinland2018Workshops__andreyAndArtemWorkshop,
  davidKhourshidWorkshop: reactFinland2018Workshops__davidKhourshidWorkshop,
  gantLabordeWorkshop: reactFinland2018Workshops__gantLabordeWorkshop,
  juhoVepsalainenWorkshop: reactFinland2018Workshops__juhoVepsalainenWorkshop,
  michelWeststrateWorkshop: reactFinland2018Workshops__michelWeststrateWorkshop,
  patrickAndNikWorkshop: reactFinland2018Workshops__patrickAndNikWorkshop,
  rotemMizrachiMeidanWorkshop: reactFinland2018Workshops__rotemMizrachiMeidanWorkshop,
  saraVieiraWorkshop: reactFinland2018Workshops__saraVieiraWorkshop,
  siaKaramalegosWorkshop: reactFinland2018Workshops__siaKaramalegosWorkshop,
  svenSauleauWorkshop: reactFinland2018Workshops__svenSauleauWorkshop,
} as const;

import reactFinland2019Talks__andreyOkonetchnikov from "./react-finland-2019/talks/andrey-okonetchnikov";
import reactFinland2019Talks__annaDoubkova from "./react-finland-2019/talks/anna-doubkova";
import reactFinland2019Talks__artemSapegin from "./react-finland-2019/talks/artem-sapegin";
import reactFinland2019Talks__artemZakharchenko from "./react-finland-2019/talks/artem-zakharchenko";
import reactFinland2019Talks__bohdanLiashenko from "./react-finland-2019/talks/bohdan-liashenko";
import reactFinland2019Talks__brunoLourenco from "./react-finland-2019/talks/bruno-lourenco";
import reactFinland2019Talks__carolynStransky from "./react-finland-2019/talks/carolyn-stransky";
import reactFinland2019Talks__christofferNiska from "./react-finland-2019/talks/christoffer-niska";
import reactFinland2019Talks__davidKhourshid from "./react-finland-2019/talks/david-khourshid";
import reactFinland2019Talks__dustinSchau from "./react-finland-2019/talks/dustin-schau";
import reactFinland2019Talks__farzadYz from "./react-finland-2019/talks/farzad-yz";
import reactFinland2019Talks__glennReyes from "./react-finland-2019/talks/glenn-reyes";
import reactFinland2019Talks__jamonHolmgren from "./react-finland-2019/talks/jamon-holmgren";
import reactFinland2019Talks__juhaLinnanen from "./react-finland-2019/talks/juha-linnanen";
import reactFinland2019Talks__kadiKraman from "./react-finland-2019/talks/kadi-kraman";
import reactFinland2019Talks__lucaMatteis from "./react-finland-2019/talks/luca-matteis";
import reactFinland2019Talks__maaretPyhajarvi from "./react-finland-2019/talks/maaret-pyhajarvi";
import reactFinland2019Talks__manuelMatuzovic from "./react-finland-2019/talks/manuel-matuzovic";
import reactFinland2019Talks__michelWeststrate from "./react-finland-2019/talks/michel-weststrate";
import reactFinland2019Talks__monicaLent from "./react-finland-2019/talks/monica-lent";
import reactFinland2019Talks__nikGraf from "./react-finland-2019/talks/nik-graf";
import reactFinland2019Talks__rickHanlon from "./react-finland-2019/talks/rick-hanlon";
import reactFinland2019Talks__svenSauleau from "./react-finland-2019/talks/sven-sauleau";
import reactFinland2019Talks__tejasKumar from "./react-finland-2019/talks/tejas-kumar";
import reactFinland2019Talks__tomasKonrady from "./react-finland-2019/talks/tomas-konrady";
import reactFinland2019Talks__varyaStepanova from "./react-finland-2019/talks/varya-stepanova";
import reactFinland2019Talks__villeImmonen from "./react-finland-2019/talks/ville-immonen";

export const reactFinland2019Talks = {
  andreyOkonetchnikov: reactFinland2019Talks__andreyOkonetchnikov,
  annaDoubkova: reactFinland2019Talks__annaDoubkova,
  artemSapegin: reactFinland2019Talks__artemSapegin,
  artemZakharchenko: reactFinland2019Talks__artemZakharchenko,
  bohdanLiashenko: reactFinland2019Talks__bohdanLiashenko,
  brunoLourenco: reactFinland2019Talks__brunoLourenco,
  carolynStransky: reactFinland2019Talks__carolynStransky,
  christofferNiska: reactFinland2019Talks__christofferNiska,
  davidKhourshid: reactFinland2019Talks__davidKhourshid,
  dustinSchau: reactFinland2019Talks__dustinSchau,
  farzadYz: reactFinland2019Talks__farzadYz,
  glennReyes: reactFinland2019Talks__glennReyes,
  jamonHolmgren: reactFinland2019Talks__jamonHolmgren,
  juhaLinnanen: reactFinland2019Talks__juhaLinnanen,
  kadiKraman: reactFinland2019Talks__kadiKraman,
  lucaMatteis: reactFinland2019Talks__lucaMatteis,
  maaretPyhajarvi: reactFinland2019Talks__maaretPyhajarvi,
  manuelMatuzovic: reactFinland2019Talks__manuelMatuzovic,
  michelWeststrate: reactFinland2019Talks__michelWeststrate,
  monicaLent: reactFinland2019Talks__monicaLent,
  nikGraf: reactFinland2019Talks__nikGraf,
  rickHanlon: reactFinland2019Talks__rickHanlon,
  svenSauleau: reactFinland2019Talks__svenSauleau,
  tejasKumar: reactFinland2019Talks__tejasKumar,
  tomasKonrady: reactFinland2019Talks__tomasKonrady,
  varyaStepanova: reactFinland2019Talks__varyaStepanova,
  villeImmonen: reactFinland2019Talks__villeImmonen,
} as const;

import reactFinland2019Workshops__andreyAndArtemWorkshop from "./react-finland-2019/workshops/andrey-and-artem-workshop";
import reactFinland2019Workshops__davidKhourshidWorkshop from "./react-finland-2019/workshops/david-khourshid-workshop";
import reactFinland2019Workshops__glennReyesWorkshop from "./react-finland-2019/workshops/glenn-reyes-workshop";
import reactFinland2019Workshops__michelWorkshop from "./react-finland-2019/workshops/michel-workshop";
import reactFinland2019Workshops__nikWorkshop from "./react-finland-2019/workshops/nik-workshop";
import reactFinland2019Workshops__performanceWorkshop from "./react-finland-2019/workshops/performance-workshop";

export const reactFinland2019Workshops = {
  andreyAndArtemWorkshop: reactFinland2019Workshops__andreyAndArtemWorkshop,
  davidKhourshidWorkshop: reactFinland2019Workshops__davidKhourshidWorkshop,
  glennReyesWorkshop: reactFinland2019Workshops__glennReyesWorkshop,
  michelWorkshop: reactFinland2019Workshops__michelWorkshop,
  nikWorkshop: reactFinland2019Workshops__nikWorkshop,
  performanceWorkshop: reactFinland2019Workshops__performanceWorkshop,
} as const;

import reactFinland2020Talks__brent from "./react-finland-2020/talks/brent";
import reactFinland2020Talks__davidKhourshid from "./react-finland-2020/talks/david-khourshid";
import reactFinland2020Talks__eli from "./react-finland-2020/talks/eli";
import reactFinland2020Talks__emma from "./react-finland-2020/talks/emma";
import reactFinland2020Talks__esaMatti from "./react-finland-2020/talks/esa-matti";
import reactFinland2020Talks__farzadYz from "./react-finland-2020/talks/farzad-yz";
import reactFinland2020Talks__isaSilveira from "./react-finland-2020/talks/isa-silveira";
import reactFinland2020Talks__ivanOrlov from "./react-finland-2020/talks/ivan-orlov";
import reactFinland2020Talks__jaredPalmer from "./react-finland-2020/talks/jared-palmer";
import reactFinland2020Talks__jeremyWagner from "./react-finland-2020/talks/jeremy-wagner";
import reactFinland2020Talks__kenigboloMeyaStephen from "./react-finland-2020/talks/kenigbolo-meya-stephen";
import reactFinland2020Talks__kennethSutherland from "./react-finland-2020/talks/kenneth-sutherland";
import reactFinland2020Talks__kentCDodds from "./react-finland-2020/talks/kent-c-dodds";
import reactFinland2020Talks__lauraGonzalez from "./react-finland-2020/talks/laura-gonzalez";
import reactFinland2020Talks__lauri from "./react-finland-2020/talks/lauri";
import reactFinland2020Talks__madalyn from "./react-finland-2020/talks/madalyn";
import reactFinland2020Talks__margarita from "./react-finland-2020/talks/margarita";
import reactFinland2020Talks__naderDabit from "./react-finland-2020/talks/nader-dabit";
import reactFinland2020Talks__nikGraf from "./react-finland-2020/talks/nik-graf";
import reactFinland2020Talks__olavi from "./react-finland-2020/talks/olavi";
import reactFinland2020Talks__rachelNabors from "./react-finland-2020/talks/rachel-nabors";
import reactFinland2020Talks__rebeccaHill from "./react-finland-2020/talks/rebecca-hill";
import reactFinland2020Talks__taelurAlexis from "./react-finland-2020/talks/taelur-alexis";
import reactFinland2020Talks__tejasKumar from "./react-finland-2020/talks/tejas-kumar";
import reactFinland2020Talks__tobiasTimm from "./react-finland-2020/talks/tobias-timm";
import reactFinland2020Talks__villePelkonen from "./react-finland-2020/talks/ville-pelkonen";
import reactFinland2020Talks__vivekNayyar from "./react-finland-2020/talks/vivek-nayyar";
import reactFinland2020Talks__xiaoru from "./react-finland-2020/talks/xiaoru";
import reactFinland2020Talks__yan from "./react-finland-2020/talks/yan";

export const reactFinland2020Talks = {
  brent: reactFinland2020Talks__brent,
  davidKhourshid: reactFinland2020Talks__davidKhourshid,
  eli: reactFinland2020Talks__eli,
  emma: reactFinland2020Talks__emma,
  esaMatti: reactFinland2020Talks__esaMatti,
  farzadYz: reactFinland2020Talks__farzadYz,
  isaSilveira: reactFinland2020Talks__isaSilveira,
  ivanOrlov: reactFinland2020Talks__ivanOrlov,
  jaredPalmer: reactFinland2020Talks__jaredPalmer,
  jeremyWagner: reactFinland2020Talks__jeremyWagner,
  kenigboloMeyaStephen: reactFinland2020Talks__kenigboloMeyaStephen,
  kennethSutherland: reactFinland2020Talks__kennethSutherland,
  kentCDodds: reactFinland2020Talks__kentCDodds,
  lauraGonzalez: reactFinland2020Talks__lauraGonzalez,
  lauri: reactFinland2020Talks__lauri,
  madalyn: reactFinland2020Talks__madalyn,
  margarita: reactFinland2020Talks__margarita,
  naderDabit: reactFinland2020Talks__naderDabit,
  nikGraf: reactFinland2020Talks__nikGraf,
  olavi: reactFinland2020Talks__olavi,
  rachelNabors: reactFinland2020Talks__rachelNabors,
  rebeccaHill: reactFinland2020Talks__rebeccaHill,
  taelurAlexis: reactFinland2020Talks__taelurAlexis,
  tejasKumar: reactFinland2020Talks__tejasKumar,
  tobiasTimm: reactFinland2020Talks__tobiasTimm,
  villePelkonen: reactFinland2020Talks__villePelkonen,
  vivekNayyar: reactFinland2020Talks__vivekNayyar,
  xiaoru: reactFinland2020Talks__xiaoru,
  yan: reactFinland2020Talks__yan,
} as const;

import reactFinland2020Workshops__advancedReact from "./react-finland-2020/workshops/advanced-react";
import reactFinland2020Workshops__designSystems101 from "./react-finland-2020/workshops/design-systems-101";
import reactFinland2020Workshops__designSystems from "./react-finland-2020/workshops/design-systems";
import reactFinland2020Workshops__fromLegacyToReact from "./react-finland-2020/workshops/from-legacy-to-react";
import reactFinland2020Workshops__fullStack from "./react-finland-2020/workshops/full-stack";
import reactFinland2020Workshops__modernForms from "./react-finland-2020/workshops/modern-forms";
import reactFinland2020Workshops__reactNative from "./react-finland-2020/workshops/react-native";
import reactFinland2020Workshops__reactPerformance from "./react-finland-2020/workshops/react-performance";
import reactFinland2020Workshops__resilientLibs from "./react-finland-2020/workshops/resilient-libs";
import reactFinland2020Workshops__statecharts from "./react-finland-2020/workshops/statecharts";
import reactFinland2020Workshops__testingReact from "./react-finland-2020/workshops/testing-react";

export const reactFinland2020Workshops = {
  advancedReact: reactFinland2020Workshops__advancedReact,
  designSystems101: reactFinland2020Workshops__designSystems101,
  designSystems: reactFinland2020Workshops__designSystems,
  fromLegacyToReact: reactFinland2020Workshops__fromLegacyToReact,
  fullStack: reactFinland2020Workshops__fullStack,
  modernForms: reactFinland2020Workshops__modernForms,
  reactNative: reactFinland2020Workshops__reactNative,
  reactPerformance: reactFinland2020Workshops__reactPerformance,
  resilientLibs: reactFinland2020Workshops__resilientLibs,
  statecharts: reactFinland2020Workshops__statecharts,
  testingReact: reactFinland2020Workshops__testingReact,
} as const;

import rf202001Talks__carolyn from "./rf2020-01/talks/carolyn";
import rf202001Talks__kenigboloMeyaStephen from "./rf2020-01/talks/kenigbolo-meya-stephen";
import rf202001Talks__margarita from "./rf2020-01/talks/margarita";

export const rf202001Talks = {
  carolyn: rf202001Talks__carolyn,
  kenigboloMeyaStephen: rf202001Talks__kenigboloMeyaStephen,
  margarita: rf202001Talks__margarita,
} as const;
