export default {
  APOLLO: "Apollo",
  BABEL: "Babel",
  CEREBRAL: "Cerebral",
  CMS: "CMS",
  CODE_QUALITY: "Code quality",
  DETOX: "Detox",
  GRAPHQL: "GraphQL",
  GRAPHQLJS: "graphql-js",
  IMMER: "Immer",
  LEGACY: "Legacy",
  LINTING: "Linting",
  NEXT_JS: "Next.js",
  MOBX: "MobX",
  MOBX_STATE_TREE: "mobx-state-tree",
  POSTGRAPHILE: "PostGraphile",
  PRISMA: "Prisma",
  REACT: "React",
  REACT_NATIVE: "React Native",
  REACT_VR: "React VR",
  REDUX: "Redux",
  REASON: "Reason",
  SSR: "Server Side Rendering",
  SPEC: "Specification",
  STATE_MANAGEMENT: "State management",
  STATIC_SITE_GENERATATION: "Static site generation",
  STYLING: "Styling",
  STYLEGUIDIST: "Styleguidist",
  STYLE_GUIDES: "Style guides",
  TESTING: "Testing",
  TOOLING: "Tooling",
  UNIVERSAL_REACT: "Universal React",
  WEBPACK: "Webpack",
};
