module.exports = {
  APOLLO: "Apollo",
  CODE_QUALITY: "Code quality",
  GRAPHQL: "GraphQL",
  GRAPHQLJS: "graphql-js",
  CMS: "CMS",
  LEGACY: "Legacy",
  POSTGRAPHILE: "PostGraphile",
  REACT: "React",
  REACT_NATIVE: "React Native",
  REACT_VR: "React VR",
  REASON: "Reason",
  STATE_MANAGEMENT: "State management",
  SPEC: "GraphQL Specification",
  PRISMA: "Prisma",
};
