export default {
  BRONZE_SPONSOR: "bronzeSponsor",
  GOLD_SPONSOR: "goldSponsor",
  KEYNOTE: "keynote",
  LIGHTNING_TALK: "lightningTalk",
  ORGANIZER: "organizer",
  PARTNER: "partner",
  SILVER_SPONSOR: "silverSponsor",
  SPEAKER: "speaker",
  TALK: "talk",
  WORKSHOP: "workshop",
  WORKSHOP_HOST: "workshop_host",
  COFFEE_BREAK: "coffee_break",
  LUNCH: "lunch",
  BREAKFAST: "breakfast",
  ORGANIZATIONAL: "organizational",
  PANEL: "panel",
  PARTY: "party",
};
