enum SessionType {
  TALK = "TALK",
  LIGHTNING_TALK = "LIGHTNING_TALK",
  KEYNOTE = "KEYNOTE",
  WORKSHOP = "WORKSHOP",
  PANEL = "PANEL",
  BREAKFAST = "BREAKFAST",
  LUNCH = "LUNCH",
  COFFEE_BREAK = "COFFEE_BREAK",
  ORGANIZATIONAL = "ORGANIZATIONAL",
  PARTY = "PARTY",
}

export default SessionType;
