import * as fs from "node:fs";
import * as path from "node:path";
import { globSync } from "glob";
import mri from "mri";

interface CliOptions {
  _: string[];
  verbose: boolean;
}

interface Registry {
  directory: string;
  entries: RegistryEntry[];
  exportName: string;
}

interface RegistryEntry {
  exportName: string;
  importName: string;
  importPath: string;
}

function main() {
  const args = mri<CliOptions>(process.argv.slice(2), {
    boolean: ["verbose"],
    default: {
      verbose: false,
    },
  });
  const contentRoot = path.resolve(args._[0] || "content");
  const outputPath = path.join(contentRoot, "generated.ts");
  const registries = discoverRegistries(contentRoot);
  const content = renderGeneratedModule(registries);

  writeFile(outputPath, content, args.verbose);
}

function discoverRegistries(contentRoot: string): Registry[] {
  const directories = discoverRegistryDirectories(contentRoot);

  return directories.map((directory) => ({
    directory,
    entries: discoverEntries(contentRoot, directory),
    exportName: toRegistryName(directory),
  }));
}

function discoverRegistryDirectories(contentRoot: string): string[] {
  const topLevelDirectories = ["locations", "people", "sponsors"].filter((dir) =>
    fs.existsSync(path.join(contentRoot, dir))
  );
  const sessionDirectories = globSync("**/{talks,workshops}", {
    cwd: contentRoot,
  });

  return topLevelDirectories
    .concat(sessionDirectories)
    .map(normalizePath)
    .sort((left, right) => left.localeCompare(right));
}

function discoverEntries(
  contentRoot: string,
  directory: string
): RegistryEntry[] {
  const registryName = toRegistryName(directory);

  return globSync(`${directory}/*.ts`, { cwd: contentRoot })
    .map(normalizePath)
    .filter((entryPath) => path.basename(entryPath, ".ts") !== "index")
    .sort((left, right) => left.localeCompare(right))
    .map((entryPath) => {
      const exportName = toCamelCase(path.basename(entryPath, ".ts"));
      const importName = `${registryName}__${exportName}`;
      const importPath = `./${entryPath.replace(/\.ts$/, "")}`;

      return {
        exportName,
        importName,
        importPath,
      };
    });
}

function renderGeneratedModule(registries: Registry[]): string {
  const lines = [
    "// This file is generated by `npm run generate:indices`.",
    "// Do not edit it manually.",
    "",
  ];

  registries.forEach((registry, index) => {
    registry.entries.forEach((entry) => {
      lines.push(`import ${entry.importName} from "${entry.importPath}";`);
    });

    if (registry.entries.length > 0) {
      lines.push("");
    }

    lines.push(`export const ${registry.exportName} = {`);

    registry.entries.forEach((entry) => {
      lines.push(`  ${entry.exportName}: ${entry.importName},`);
    });

    lines.push("} as const;");

    if (["locations", "people"].includes(registry.exportName)) {
      lines.push("");

      registry.entries.forEach((entry) => {
        lines.push(
          `export const ${entry.exportName} = ${registry.exportName}.${entry.exportName};`
        );
      });
    }

    if (index < registries.length - 1) {
      lines.push("");
    }
  });

  lines.push("");

  return lines.join("\n");
}

function writeFile(filePath: string, content: string, verbose: boolean) {
  const oldContent = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, { encoding: "utf8" })
    : "";

  if (content.trim() === oldContent.trim()) {
    return;
  }

  if (verbose) {
    console.log(`Writing ${filePath}`);
  }

  fs.writeFileSync(filePath, content, "utf8");
}

function toRegistryName(directory: string): string {
  if (["locations", "people", "sponsors"].includes(directory)) {
    return directory;
  }

  return toCamelCase(directory.split("/").join("-"));
}

function toCamelCase(value: string): string {
  const normalized = value
    .replace(/^[^a-zA-Z0-9]+|[^a-zA-Z0-9]+$/g, "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);

  if (normalized.length < 1) {
    return "";
  }

  return normalized
    .map((part, index) => {
      const lower = part.toLowerCase();
      const camelPart =
        index === 0
          ? lower
          : lower.charAt(0).toUpperCase() + lower.slice(1);

      return camelPart.replace(/(\d+)([a-z])/g, (_, digits, character) => {
        return `${digits}${character.toUpperCase()}`;
      });
    })
    .join("");
}

function normalizePath(filePath: string): string {
  return filePath.split(path.sep).join("/");
}

main();
