# Adapted from https://glebbahmutov.com/blog/develop-preview-test/
name: ci
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [push]
jobs:
  show-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use the right version of Node
        shell: bash -l {0}
        run: nvm install
      - name: Install modules
        run: npm install
      - name: Build API
        run: npm run build
      - name: Include the build to Git repository deployed to Heroku
        run: sh ./add-compiled-to-git.sh
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-finland-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
